name: Deploy Production

on:
  push:
    branches:
      - production/1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build:prod

      - name: Deploy to Production
        run: firebase deploy --only hosting:production --project bonfiire-38fad --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
