name: Deploy Staging

on:
  push:
    branches:
      - stage/1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build:staging

      - name: Deploy to Staging
        run: firebase deploy --only hosting:staging --project bonfiirestage --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
